name: test
on: 
  workflow_dispatch:   # Enable manual triggering
jobs:  
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Speech2Text.Api.Test

    steps: 
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install supertest, mocha, chai
      run: npm i -g -D supertest mocha chai mochawesome
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
